AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Lambda submitting submissions to FormStack
Parameters:
    Stack:
        Description: Stack name
        Type: String
        Default: content-api-formstack
    App:
        Description: Application name
        Type: String
        Default: formstack-submitter
    Stage:
        Description: Stage name
        Type: String
        AllowedValues:
            - PROD
            - CODE
        Default: CODE
    OAuthToken:
        Description: The authentication token for accessing the FormStack API
        Type: String

Resources:
    FormStackLambda:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub ${App}-${Stage}
            Handler: com.gu.formstack.FormStackLambda::handle
            Environment:
                Variables:
                    OAUTH_TOKEN: !Ref OAuthToken
            CodeUri:
                Bucket: content-api-dist
                Key: !Sub ${Stack}/${Stage}/${App}/${App}.zip
            MemorySize: 256
            Runtime: java8
            Timeout: 15
    ApiFrontend:
        Type: AWS::ApiGateway::Method
        Properties:
            AuthorizationType: NONE
            HttpMethod: POST
            ResourceId: !Ref APIResource
            RestApiId: !Ref APIRestAPI
            Integration:
                Type: AWS_PROXY
                IntegrationHttpMethod: POST
                Uri: !Sub
                  - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Arn}/invocations
                  - Arn: !GetAtt FormStackLambda.Arn
    APIRestAPI:
        Type: AWS::ApiGateway::RestApi
        Properties:
            Name: FormstackAPI
    APIResource:
        Type: AWS::ApiGateway::Resource
        Properties:
            RestApiId: !Ref APIRestAPI
            PathPart: "formstack"
            ParentId:
                Fn::GetAtt: 
                  - "APIRestAPI"
                  - "RootResourceId"